import Foundation

/// Built-in rules, derived from what actually piles up on this Mac.
enum DefaultRules {
    static let all: [Rule] = projects + devTools + browsers + apps + system

    // MARK: Projects

    static let projects: [Rule] = [
        Rule(id: "proj.next", name: "Next.js cache (.next)",
             detail: "Thư mục build/dev của Next.js. Bản dev chạy Turbopack có thể phình tới hàng chục GB; sẽ tự tạo lại khi chạy next dev/next build. Bỏ qua dự án đang chạy dev server.",
             category: .projects, safety: .safe, kind: .projectFolders,
             folderNames: [".next"], markers: ["package.json"],
             skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.jscache", name: "Cache bundler front-end",
             detail: ".turbo, .parcel-cache, .nuxt, .svelte-kit, .angular, .expo – cache của công cụ build, tự tạo lại.",
             category: .projects, safety: .safe, kind: .projectFolders,
             folderNames: [".turbo", ".parcel-cache", ".nuxt", ".svelte-kit", ".angular", ".expo"], markers: ["package.json"],
             skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.node_modules", name: "node_modules của dự án lâu không đụng tới",
             detail: "Thư viện npm/yarn/pnpm/bun. Chỉ xoá ở dự án không chỉnh sửa trong N ngày. Khi quay lại dự án chỉ cần chạy npm install.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: ["node_modules"], markers: ["package.json"], minIdleDays: 30,
             skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.deriveddata", name: "Xcode DerivedData trong dự án",
             detail: "DerivedData nằm cạnh file .xcodeproj (do build với -derivedDataPath). Tạo lại khi build.",
             category: .projects, safety: .safe, kind: .projectFolders,
             folderNames: ["DerivedData"], markers: ["*.xcodeproj", "*.xcworkspace", "project.yml", "Package.swift"],
             skipIfRunning: ["com.apple.dt.Xcode"], autoClean: true),
        Rule(id: "proj.xcodebuild", name: "Thư mục build cạnh dự án Xcode",
             detail: "Thư mục build/ cạnh .xcodeproj (output của xcodebuild, archive, IPA). Kiểm tra nếu bạn lưu file IPA ở đây.",
             category: .projects, safety: .review, kind: .projectFolders,
             folderNames: ["build"], markers: ["*.xcodeproj", "*.xcworkspace"], minIdleDays: 7,
             skipIfRunning: ["com.apple.dt.Xcode"], autoClean: false),
        Rule(id: "proj.gradle", name: "Build Android / Gradle",
             detail: "build/, .gradle/, .cxx/ của module Android. Gradle tạo lại khi build.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: ["build", ".gradle", ".cxx"],
             markers: ["build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"], minIdleDays: 7,
             skipIfRunning: ["com.google.android.studio"], skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.flutter", name: "Build Flutter / Dart",
             detail: ".dart_tool/ và build/ của dự án Flutter. Chạy flutter pub get để tạo lại.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: [".dart_tool", "build"], markers: ["pubspec.yaml"], minIdleDays: 14,
             skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.pycache", name: "Cache Python",
             detail: "__pycache__, .pytest_cache, .mypy_cache, .ruff_cache – Python tự tạo lại.",
             category: .projects, safety: .safe, kind: .projectFolders,
             folderNames: ["__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"], autoClean: true),
        Rule(id: "proj.venv", name: "Môi trường ảo Python (venv) lâu không dùng",
             detail: "Thư mục .venv/venv có pyvenv.cfg. Tạo lại bằng python -m venv và pip install -r requirements.txt.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: [".venv", "venv", "env"], markersInside: ["pyvenv.cfg"], minIdleDays: 60,
             skipIfProjectRunning: true, autoClean: false),
        Rule(id: "proj.pods", name: "CocoaPods (Pods) lâu không dùng",
             detail: "Chạy pod install để cài lại.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: ["Pods"], markers: ["Podfile"], minIdleDays: 30, autoClean: false),
        Rule(id: "proj.rust", name: "Rust target",
             detail: "Output build của Cargo.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: ["target"], markers: ["Cargo.toml"], minIdleDays: 14,
             skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.nodecache", name: "Cache trong node_modules/.cache",
             detail: "Cache của webpack, babel, eslint, Storybook, Vite… nằm trong node_modules/.cache. Tự tạo lại, dọn được cả ở dự án đang làm (trừ khi đang chạy).",
             category: .projects, safety: .safe, kind: .projectFolders,
             folderNames: ["node_modules"], markers: ["package.json"],
             skipIfProjectRunning: true, autoClean: true, subpath: ".cache"),
        Rule(id: "proj.jsdist", name: "Output build JS (dist, out, coverage…)",
             detail: "dist/, out/, .output/, coverage/, storybook-static/ của dự án JS không sửa trong N ngày. Chạy lại lệnh build để tạo lại.",
             category: .projects, safety: .review, kind: .projectFolders,
             folderNames: ["dist", "out", ".output", "coverage", "storybook-static"], markers: ["package.json"], minIdleDays: 14,
             skipIfProjectRunning: true, autoClean: false),
        Rule(id: "proj.swiftpm", name: "Swift Package build (.build)",
             detail: "Thư mục .build của Swift Package Manager. Tạo lại khi swift build.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: [".build"], markers: ["Package.swift"], minIdleDays: 14,
             skipIfProjectRunning: true, autoClean: true),
        Rule(id: "proj.terraform", name: "Terraform providers (.terraform)",
             detail: "Provider và module Terraform đã tải. Chạy terraform init để tải lại.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: [".terraform"], markers: ["*.tf"], minIdleDays: 30, autoClean: false),
        Rule(id: "proj.pytools", name: "Môi trường test Python (.tox, .nox)",
             detail: "Môi trường do tox/nox tạo ra, tự dựng lại ở lần test sau.",
             category: .projects, safety: .moderate, kind: .projectFolders,
             folderNames: [".tox", ".nox"], markers: ["tox.ini", "noxfile.py", "pyproject.toml", "setup.py"], minIdleDays: 30,
             autoClean: false),
    ]

    // MARK: Developer tools

    static let devTools: [Rule] = [
        Rule(id: "dev.xcode.derived", name: "Xcode DerivedData",
             detail: "Kết quả build trung gian của Xcode. Tạo lại ở lần build sau.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Developer/Xcode/DerivedData"],
             skipIfRunning: ["com.apple.dt.Xcode"], autoClean: true),
        Rule(id: "dev.xcode.devicesupport", name: "Xcode Device Support cũ",
             detail: "Symbol của các phiên bản iOS/watchOS từng cắm máy. Xcode tải lại khi cắm thiết bị.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/Library/Developer/Xcode/iOS DeviceSupport", "~/Library/Developer/Xcode/watchOS DeviceSupport",
                     "~/Library/Developer/Xcode/tvOS DeviceSupport", "~/Library/Developer/Xcode/visionOS DeviceSupport"],
             olderThanDays: 90, autoClean: true),
        Rule(id: "dev.xcode.archives", name: "Xcode Archives cũ",
             detail: "Bản archive đã build để phát hành. Cần giữ nếu muốn symbolicate crash của bản cũ.",
             category: .devTools, safety: .review, kind: .contents,
             paths: ["~/Library/Developer/Xcode/Archives"], olderThanDays: 180,
             deleteMode: .trash, autoClean: false),
        Rule(id: "dev.sim.unavailable", name: "Simulator không còn dùng được",
             detail: "Xoá thiết bị Simulator thuộc runtime đã gỡ (xcrun simctl delete unavailable).",
             category: .devTools, safety: .safe, kind: .command,
             command: "xcrun simctl delete unavailable", autoClean: true),
        Rule(id: "dev.sim.caches", name: "Cache & log CoreSimulator",
             detail: "Cache và log của Simulator.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Developer/CoreSimulator/Caches", "~/Library/Logs/CoreSimulator"],
             skipIfRunning: ["com.apple.iphonesimulator"], autoClean: true),
        Rule(id: "dev.npm", name: "Cache npm",
             detail: "~/.npm/_cacache và log. npm tải lại gói khi cần.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/.npm/_cacache", "~/.npm/_logs"], autoClean: true),
        Rule(id: "dev.npx", name: "Gói npx lâu không dùng",
             detail: "Mỗi lệnh npx lưu một bản cài riêng trong ~/.npm/_npx. Chỉ xoá bản không chạy trong N ngày.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/.npm/_npx"], olderThanDays: 14, autoClean: true),
        Rule(id: "dev.pkgcaches", name: "Cache trình quản lý gói",
             detail: "pip, uv, Poetry, Yarn, React Native/Hermes, dotslash, pnpm, bun, Deno, nvm, Composer, node-gyp, electron-builder, SwiftPM, CocoaPods, Go build cache.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches/pip", "~/.cache/pip", "~/Library/Caches/Yarn", "~/Library/Caches/pnpm",
                     "~/.bun/install/cache", "~/.nvm/.cache", "~/Library/Caches/node-gyp",
                     "~/Library/Caches/electron-builder", "~/Library/Caches/electron", "~/Library/Caches/org.swift.swiftpm",
                     "~/Library/Caches/CocoaPods", "~/Library/Caches/go-build", "~/Library/Caches/typescript",
                     "~/Library/Caches/uv", "~/.cache/uv", "~/Library/Caches/pypoetry", "~/Library/Caches/deno",
                     "~/.yarn/berry/cache", "~/.cache/yarn", "~/Library/Caches/composer",
                     "~/Library/Caches/ReactNative", "~/Library/Caches/dotslash"],
             autoClean: true),
        Rule(id: "dev.pnpmstore", name: "pnpm store",
             detail: "Kho gói dùng chung của pnpm. Xoá xong lần cài sau phải tải lại toàn bộ.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/Library/pnpm/store"], autoClean: false),
        Rule(id: "dev.homebrew", name: "Homebrew cleanup",
             detail: "Xoá phiên bản cũ và file tải về của Homebrew (brew cleanup --prune=all -s).",
             category: .devTools, safety: .safe, kind: .command,
             command: "brew cleanup --prune=all -s", autoClean: true),
        Rule(id: "dev.gradle", name: "Gradle cache & bản Gradle cũ",
             detail: "Thư mục trong ~/.gradle (caches, wrapper, daemon) không dùng trong N ngày.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/.gradle/caches", "~/.gradle/wrapper/dists", "~/.gradle/daemon"],
             excludeNames: ["CACHEDIR.TAG", "*.lock"], olderThanDays: 30, autoClean: true),
        Rule(id: "dev.headless", name: "Profile Chrome headless sót lại",
             detail: "Thư mục scoped_dir… do Puppeteer/Playwright/automation tạo ra mà không dọn.",
             category: .devTools, safety: .safe, kind: .paths,
             paths: ["~/Library/Caches/Google/Chrome-headless/*", "$TMPDIR/puppeteer_dev_*", "$TMPDIR/playwright*",
                     "$TMPDIR/.org.chromium.Chromium.*"],
             olderThanDays: 1, autoClean: true),
        Rule(id: "dev.tmp", name: "Cache tạm của Metro / Node",
             detail: "metro-cache, haste-map, node-compile-cache, tsx trong thư mục tạm.",
             category: .devTools, safety: .safe, kind: .paths,
             paths: ["$TMPDIR/metro-*", "$TMPDIR/haste-map-*", "$TMPDIR/node-compile-cache", "$TMPDIR/tsx-*",
                     "$TMPDIR/v8-compile-cache-*"],
             olderThanDays: 3, autoClean: true),
        Rule(id: "dev.codexlogs", name: "Log của Codex",
             detail: "~/.codex/logs_*.sqlite tăng dần theo thời gian. Codex tạo lại file mới.",
             category: .devTools, safety: .review, kind: .paths,
             paths: ["~/.codex/logs_*.sqlite", "~/.codex/logs_*.sqlite-wal", "~/.codex/logs_*.sqlite-shm", "~/.codex/log/*"],
             skipIfRunning: ["com.openai.codex", "codex"], autoClean: false),
        Rule(id: "dev.xcode.misc", name: "Xcode Previews, Products & cache",
             detail: "Bản build của SwiftUI Previews, thư mục Products và cache của Xcode. Tạo lại khi cần.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Developer/Xcode/UserData/Previews", "~/Library/Developer/Xcode/Products",
                     "~/Library/Caches/com.apple.dt.Xcode"],
             skipIfRunning: ["com.apple.dt.Xcode"], autoClean: true),
        Rule(id: "dev.sim.runtimes", name: "Runtime Simulator lâu không dùng",
             detail: "Gỡ runtime iOS/watchOS Simulator không dùng trong 90 ngày (xcrun simctl runtime delete --notUsedSinceDays 90). Mỗi runtime ~8 GB, tải lại trong Xcode → Settings → Components.",
             category: .devTools, safety: .moderate, kind: .command,
             command: "xcrun simctl runtime delete --notUsedSinceDays 90", autoClean: false),
        Rule(id: "dev.sim.erase", name: "Xoá sạch dữ liệu mọi Simulator",
             detail: "Đưa mọi thiết bị Simulator về như mới: xoá app đã cài, ảnh, dữ liệu. Các thiết bị vẫn được giữ.",
             category: .devTools, safety: .review, kind: .command,
             command: "xcrun simctl shutdown all; xcrun simctl erase all",
             skipIfRunning: ["com.apple.iphonesimulator"], autoClean: false),
        Rule(id: "dev.docker", name: "Docker: container, image, build cache thừa",
             detail: "docker system prune -f: container đã dừng, network thừa, image lơ lửng, build cache. Không xoá volume.",
             category: .devTools, safety: .moderate, kind: .command,
             command: "docker system prune -f", autoClean: false),
        Rule(id: "dev.gomod", name: "Go module cache",
             detail: "go clean -modcache. Lần build sau sẽ tải lại module.",
             category: .devTools, safety: .moderate, kind: .command,
             command: "go clean -modcache", autoClean: false),
        Rule(id: "dev.conda", name: "Conda: gói đã tải",
             detail: "conda clean --all --yes: tarball, gói không dùng, cache index.",
             category: .devTools, safety: .safe, kind: .command,
             command: "conda clean --all --yes", autoClean: false),
        Rule(id: "dev.cargo", name: "Cargo registry cache",
             detail: "Crate Rust đã tải và giải nén không dùng trong N ngày.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/.cargo/registry/cache", "~/.cargo/registry/src", "~/.cargo/git/checkouts"],
             olderThanDays: 30, autoClean: true),
        Rule(id: "dev.maven", name: "Maven repository cũ",
             detail: "Thư viện trong ~/.m2/repository không dùng trong N ngày.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/.m2/repository/*"], olderThanDays: 90, autoClean: false),
        Rule(id: "dev.android", name: "Cache Android SDK & Android Studio",
             detail: "~/.android/cache, build-cache và cache của Android Studio.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/.android/cache", "~/.android/build-cache", "~/Library/Caches/Google/AndroidStudio*"],
             skipIfRunning: ["com.google.android.studio"], autoClean: true),
        Rule(id: "dev.jetbrains", name: "Cache & log JetBrains bản cũ",
             detail: "Cache của các phiên bản IntelliJ/WebStorm/PyCharm… không dùng trong N ngày (thường là bản IDE đã nâng cấp).",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches/JetBrains", "~/Library/Logs/JetBrains"], olderThanDays: 30, autoClean: true),
        Rule(id: "dev.ide-workspace", name: "Workspace cũ của VS Code / Cursor",
             detail: "Trạng thái giao diện và lịch sử cục bộ của các thư mục không mở trong N ngày.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/Library/Application Support/{Code,Cursor,Antigravity,Windsurf}/User/workspaceStorage"],
             olderThanDays: 60, autoClean: false),
        Rule(id: "dev.ide-logs", name: "Log VS Code / Cursor / Discord",
             detail: "Thư mục log theo ngày của các app Electron.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Application Support/{Code,Cursor,Antigravity,Windsurf,discord}/logs"],
             olderThanDays: 7, autoClean: true),
        Rule(id: "dev.browsers-automation", name: "Trình duyệt Playwright / Puppeteer cũ",
             detail: "Các bản Chromium/Firefox/WebKit tải về cho test tự động mà không chạy trong N ngày.",
             category: .devTools, safety: .moderate, kind: .contents,
             paths: ["~/Library/Caches/ms-playwright", "~/.cache/ms-playwright", "~/.cache/puppeteer/chrome",
                     "~/.cache/puppeteer/chrome-headless-shell", "~/.cache/puppeteer/firefox"],
             olderThanDays: 60, autoClean: false),
        Rule(id: "dev.ml-models", name: "Model AI/ML đã tải",
             detail: "Model HuggingFace, PyTorch, EasyOCR, PaddleX, Whisper… không dùng trong N ngày. Tải lại có thể lâu.",
             category: .devTools, safety: .review, kind: .contents,
             paths: ["~/.cache/huggingface/hub", "~/.cache/torch/hub", "~/.EasyOCR/model", "~/.paddlex/official_models",
                     "~/.cache/whisper", "~/.u2net"],
             olderThanDays: 60, autoClean: false),
        Rule(id: "dev.old-versions", name: "Phiên bản cũ của Claude Code",
             detail: "Mỗi lần cập nhật để lại một bản cũ. Luôn giữ bản mới nhất và bỏ qua bản đang chạy.",
             category: .devTools, safety: .safe, kind: .contents,
             paths: ["~/Library/Application Support/Claude/claude-code", "~/Library/Application Support/Claude/claude-code-vm",
                     "~/.local/share/claude/versions"],
             autoClean: true, keepNewest: 1, skipIfInUse: true),
        Rule(id: "dev.codex-tmp", name: "Bản cài Codex runtime dang dở",
             detail: "Thư mục codex-runtime-install-* còn sót sau khi cài runtime.",
             category: .devTools, safety: .safe, kind: .paths,
             paths: ["~/.cache/codex-runtimes/codex-runtime-install-*"], olderThanDays: 1,
             autoClean: true, skipIfInUse: true),
        Rule(id: "dev.codex-sessions", name: "Phiên làm việc Codex cũ",
             detail: "Lịch sử hội thoại Codex trong ~/.codex/sessions cũ hơn N ngày.",
             category: .devTools, safety: .review, kind: .contents,
             paths: ["~/.codex/sessions/*/*"], olderThanDays: 90, autoClean: false),
    ]

    // MARK: Browsers

    static let browsers: [Rule] = [
        Rule(id: "web.chrome", name: "Cache Google Chrome",
             detail: "Cache trang web, mã JS, shader của mọi profile. Không ảnh hưởng mật khẩu, lịch sử, cookie.",
             category: .browsers, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches/Google/Chrome/*/Cache", "~/Library/Caches/Google/Chrome/*/Code Cache",
                     "~/Library/Caches/Google/Chrome/*/image_cache", "~/Library/Caches/Google/Chrome/*/*/Cache",
                     "~/Library/Application Support/Google/Chrome/*/GPUCache",
                     "~/Library/Application Support/Google/Chrome/GrShaderCache",
                     "~/Library/Application Support/Google/Chrome/GraphiteDawnCache",
                     "~/Library/Application Support/Google/Chrome/ShaderCache"],
             skipIfRunning: ["com.google.Chrome"], autoClean: true),
        Rule(id: "web.chrome.sw", name: "Chrome Service Worker cache",
             detail: "Dữ liệu offline của các web app (PWA). Xoá thì trang sẽ tải lại từ đầu.",
             category: .browsers, safety: .moderate, kind: .contents,
             paths: ["~/Library/Application Support/Google/Chrome/*/Service Worker/CacheStorage",
                     "~/Library/Application Support/Google/Chrome/*/Service Worker/ScriptCache"],
             skipIfRunning: ["com.google.Chrome"], autoClean: false),
        Rule(id: "web.googleupdater", name: "Google Updater – gói cập nhật đã tải",
             detail: "File cài đặt cập nhật Chrome đã dùng xong (crx_cache).",
             category: .browsers, safety: .safe, kind: .contents,
             paths: ["~/Library/Application Support/Google/GoogleUpdater/crx_cache"], autoClean: true),
        Rule(id: "web.safari", name: "Cache Safari",
             detail: "Cần cấp Full Disk Access để đọc.",
             category: .browsers, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches/com.apple.Safari"],
             skipIfRunning: ["com.apple.Safari"], autoClean: false),
        Rule(id: "web.others", name: "Cache trình duyệt khác",
             detail: "Brave, Edge, Firefox, Arc, Opera, DuckDuckGo.",
             category: .browsers, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches/BraveSoftware/Brave-Browser/*/Cache", "~/Library/Caches/Microsoft Edge/*/Cache",
                     "~/Library/Caches/Firefox/Profiles/*/cache2", "~/Library/Caches/company.thebrowser.Browser",
                     "~/Library/Caches/com.operasoftware.Opera", "~/Library/Caches/com.duckduckgo.macos.browser"],
             skipIfRunning: ["com.brave.Browser", "com.microsoft.edgemac", "org.mozilla.firefox",
                             "company.thebrowser.Browser", "com.operasoftware.Opera", "com.duckduckgo.macos.browser",
                            "JetBrains", "com.spotify.client", "Adobe", "*.ShipIt", "uv", "pypoetry", "deno", "composer", "ReactNative", "dotslash"],
             autoClean: true),
        Rule(id: "web.chrome.components", name: "Thành phần & model AI của Chrome",
             detail: "Model Gemini Nano, OCR, gói component Chrome tự tải. Chrome sẽ tải lại khi cần.",
             category: .browsers, safety: .moderate, kind: .paths,
             paths: ["~/Library/Application Support/Google/Chrome/OptGuideOnDeviceModel",
                     "~/Library/Application Support/Google/Chrome/optimization_guide_model_store",
                     "~/Library/Application Support/Google/Chrome/component_crx_cache",
                     "~/Library/Application Support/Google/Chrome/screen_ai"],
             skipIfRunning: ["com.google.Chrome"], autoClean: false),
    ]

    // MARK: Apps

    static let telegramRoot = "~/Library/Group Containers/6N38VWS5BX.ru.keepcoder.Telegram/stable/account-*/postbox/media"
    static let zaloRoot = "~/Library/Application Support/ZaloData"

    static let apps: [Rule] = [
        Rule(id: "app.telegram", name: "Media cache Telegram",
             detail: "Ảnh/video/file đã xem trên Telegram. Dữ liệu vẫn nằm trên cloud của Telegram, mở lại sẽ tự tải về.",
             category: .apps, safety: .moderate, kind: .contents,
             paths: [telegramRoot, telegramRoot + "/cache", telegramRoot + "/short-cache"],
             olderThanDays: 30, skipIfRunning: ["ru.keepcoder.Telegram"], autoClean: true),
        Rule(id: "app.zalo.cache", name: "Cache Zalo",
             detail: "Cache trình duyệt, ảnh thu nhỏ và gói cập nhật cũ của Zalo.",
             category: .apps, safety: .safe, kind: .contents,
             paths: [zaloRoot + "/Cache", zaloRoot + "/Code Cache", zaloRoot + "/GPUCache",
                     zaloRoot + "/media/update", zaloRoot + "/media/temp",
                     zaloRoot + "/media/*/ZaloDownloads/richThumb", zaloRoot + "/media/*/ZaloDownloads/fileThumb",
                     zaloRoot + "/media/*/ZaloDownloads/Cache", "~/Library/Caches/com.vng.zalo"],
             skipIfRunning: ["com.vng.zalo"], autoClean: true),
        Rule(id: "app.zalo.media", name: "File, ảnh, video Zalo đã tải (cũ)",
             detail: "File nhận qua Zalo được lưu trên máy. Có thể KHÔNG tải lại được nếu đã hết hạn trên server Zalo. Mặc định chuyển vào Thùng rác.",
             category: .apps, safety: .review, kind: .contents,
             paths: [zaloRoot + "/media/*/ZaloDownloads/resource", zaloRoot + "/media/*/ZaloDownloads/resource/*",
                     zaloRoot + "/media/*/ZaloDownloads/file", zaloRoot + "/media/*/ZaloDownloads/picture",
                     zaloRoot + "/media/*/ZaloDownloads/video", zaloRoot + "/media/*/ZaloDownloads/voice"],
             olderThanDays: 180, skipIfRunning: ["com.vng.zalo"], deleteMode: .trash, autoClean: false),
        electron("app.discord", "Discord", folder: "discord", bundleID: "com.hnc.Discord", extra: ["download"]),
        electron("app.claude", "Claude", folder: "Claude", bundleID: "com.anthropic.claudefordesktop"),
        electron("app.figma", "Figma", folder: "Figma/DesktopProfile/*", bundleID: "com.figma.Desktop"),
        electron("app.vscode", "VS Code", folder: "Code", bundleID: "com.microsoft.VSCode", extra: ["CachedData", "CachedExtensionVSIXs"]),
        electron("app.cursor", "Cursor", folder: "Cursor", bundleID: "com.todesktop.230313mzl4w4u92", extra: ["CachedData"]),
        electron("app.antigravity", "Antigravity", folder: "Antigravity", bundleID: "com.google.antigravity", extra: ["CachedData"]),
        electron("app.slack", "Slack", folder: "Slack", bundleID: "com.tinyspeck.slackmacgap"),
        electron("app.orca", "Orca", folder: "orca", bundleID: "com.stablyai.orca"),
        electron("app.codex", "ChatGPT / Codex", folder: "Codex", bundleID: "com.openai.codex"),
        electron("app.lark", "Lark", folder: "LarkInternational", bundleID: "com.electron.lark", extra: ["GrShaderCache"]),
        Rule(id: "app.updaters", name: "Gói cập nhật app đã tải",
             detail: "File cập nhật mà Zalo, Claude, Figma, Orca… tải về rồi để lại (…-updater, ….ShipIt).",
             category: .apps, safety: .safe, kind: .paths,
             paths: ["~/Library/Application Support/Caches/*-updater", "~/Library/Caches/*.ShipIt"],
             olderThanDays: 3, autoClean: true),
        Rule(id: "app.office", name: "Cache Microsoft Office / Teams",
             detail: "Cache của Word, Excel, PowerPoint, Outlook, OneNote, Teams.",
             category: .apps, safety: .safe, kind: .contents,
             paths: ["~/Library/Containers/com.microsoft.*/Data/Library/Caches"],
             skipIfRunning: ["com.microsoft.Word", "com.microsoft.Excel", "com.microsoft.Powerpoint",
                             "com.microsoft.Outlook", "com.microsoft.onenote.mac", "com.microsoft.teams2"],
             autoClean: true),
        Rule(id: "app.adobe", name: "Media cache Adobe",
             detail: "Media Cache, Peak Files của Premiere/After Effects/Audition và cache Creative Cloud.",
             category: .apps, safety: .safe, kind: .contents,
             paths: ["~/Library/Application Support/Adobe/Common/Media Cache Files",
                     "~/Library/Application Support/Adobe/Common/Media Cache",
                     "~/Library/Application Support/Adobe/Common/Peak Files", "~/Library/Caches/Adobe"],
             autoClean: true),
        Rule(id: "app.spotify", name: "Cache Spotify",
             detail: "Nhạc đã stream được lưu tạm. Không ảnh hưởng bài đã tải offline trong app.",
             category: .apps, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches/com.spotify.client"],
             skipIfRunning: ["com.spotify.client"], autoClean: true),
        Rule(id: "app.discord.old", name: "Phiên bản cũ của Discord",
             detail: "Thư mục app-x.y.z cũ còn lại sau khi Discord tự cập nhật. Giữ bản mới nhất.",
             category: .apps, safety: .safe, kind: .paths,
             paths: ["~/Library/Application Support/discord/app-*"],
             autoClean: true, keepNewest: 1, skipIfInUse: true),
        Rule(id: "app.mail", name: "File đính kèm Mail đã mở",
             detail: "Bản sao file đính kèm Mail tạo ra khi bạn mở/xem. File gốc vẫn nằm trong email. Cần Full Disk Access.",
             category: .apps, safety: .safe, kind: .contents,
             paths: ["~/Library/Containers/com.apple.mail/Data/Library/Mail Downloads"],
             skipIfRunning: ["com.apple.mail"], autoClean: false),
        Rule(id: "app.ios-backup", name: "Bản sao lưu iPhone/iPad cũ",
             detail: "Bản backup thiết bị iOS trong Finder không cập nhật trong N ngày. Đảm bảo bạn còn bản backup khác (iCloud) trước khi xoá.",
             category: .apps, safety: .review, kind: .contents,
             paths: ["~/Library/Application Support/MobileSync/Backup"], olderThanDays: 180,
             deleteMode: .trash, autoClean: false),
        Rule(id: "app.orphans", name: "Dữ liệu của app đã gỡ",
             detail: "Container, dữ liệu và trạng thái của app không còn trên máy (không thấy app nào cùng nhà phát triển). Nên xem từng mục; mặc định chuyển vào Thùng rác.",
             category: .apps, safety: .review, kind: .orphanData,
             paths: ["~/Library/Containers", "~/Library/Group Containers", "~/Library/Application Support",
                     "~/Library/Saved Application State", "~/Library/HTTPStorages", "~/Library/WebKit"],
             deleteMode: .trash, autoClean: false),
    ]

    static func electron(_ id: String, _ name: String, folder: String, bundleID: String, extra: [String] = []) -> Rule {
        let base = "~/Library/Application Support/\(folder)"
        let subfolders = ["Cache", "Code Cache", "GPUCache", "DawnGraphiteCache", "DawnWebGPUCache", "GraphiteDawnCache", "ShaderCache"] + extra
        return Rule(id: id, name: "Cache \(name)",
                    detail: "Cache Chromium/Electron của \(name) (Cache, Code Cache, GPUCache…). Tự tạo lại.",
                    category: .apps, safety: .safe, kind: .contents,
                    paths: subfolders.map { "\(base)/\($0)" },
                    skipIfRunning: [bundleID], autoClean: true)
    }

    // MARK: System

    static let system: [Rule] = [
        Rule(id: "sys.logs", name: "Log ứng dụng cũ",
             detail: "File log trong ~/Library/Logs không được ghi thêm trong N ngày.",
             category: .system, safety: .safe, kind: .contents,
             paths: ["~/Library/Logs", "~/Library/Logs/*"],
             excludeNames: ["DiagnosticReports", "CoreSimulator", "JetBrains"], olderThanDays: 14, autoClean: true),
        Rule(id: "sys.crash", name: "Báo cáo lỗi (crash report)",
             detail: "File .ips/.crash trong DiagnosticReports.",
             category: .system, safety: .safe, kind: .contents,
             paths: ["~/Library/Logs/DiagnosticReports"], olderThanDays: 7, autoClean: true),
        Rule(id: "sys.caches", name: "Cache của ứng dụng bỏ không",
             detail: "Thư mục trong ~/Library/Caches không được ứng dụng nào đụng tới trong N ngày (thường là app đã gỡ hoặc không dùng nữa).",
             category: .system, safety: .safe, kind: .contents,
             paths: ["~/Library/Caches"],
             excludeNames: ["com.apple.*", "Google", "Homebrew", "pip", "Yarn", "pnpm", "node-gyp", "electron-builder",
                            "electron", "org.swift.swiftpm", "CocoaPods", "go-build", "typescript", "BraveSoftware",
                            "Microsoft Edge", "Firefox", "ms-playwright", "com.vng.zalo", "CloudKit", "FamilyCircle",
                            "company.thebrowser.Browser", "com.operasoftware.Opera", "com.duckduckgo.macos.browser",
                            "JetBrains", "com.spotify.client", "Adobe", "*.ShipIt", "uv", "pypoetry", "deno", "composer"],
             olderThanDays: 30, autoClean: true),
        Rule(id: "sys.downloads", name: "File cài đặt cũ trong Downloads",
             detail: ".dmg, .pkg, .zip, .exe, .apk, .ipa… đã tải về hơn N ngày. Chuyển vào Thùng rác để còn khôi phục được.",
             category: .system, safety: .review, kind: .contents,
             paths: ["~/Downloads"],
             extensions: ["dmg", "pkg", "mpkg", "zip", "exe", "msi", "apk", "aab", "ipa", "xip", "iso", "rar", "7z", "tgz", "gz"],
             olderThanDays: 30, ageBasis: .added, deleteMode: .trash, autoClean: false),
        Rule(id: "sys.trash", name: "Thùng rác – mục cũ",
             detail: "Xoá vĩnh viễn những mục đã nằm trong Thùng rác hơn N ngày. Cần Full Disk Access.",
             category: .system, safety: .review, kind: .contents,
             paths: ["~/.Trash"], olderThanDays: 30, ageBasis: .added, autoClean: false),
        Rule(id: "sys.ios-updates", name: "File cập nhật iOS / iPadOS",
             detail: "File .ipsw do Finder tải về khi cập nhật iPhone/iPad.",
             category: .system, safety: .safe, kind: .contents,
             paths: ["~/Library/iTunes/iPhone Software Updates", "~/Library/iTunes/iPad Software Updates"], autoClean: true),
        Rule(id: "sys.screenshots", name: "Ảnh & video chụp màn hình cũ",
             detail: "Ảnh chụp và bản ghi màn hình trong thư mục lưu screenshot, cũ hơn N ngày. Chuyển vào Thùng rác.",
             category: .system, safety: .review, kind: .contents,
             paths: ["$SCREENSHOTS"],
             extensions: ["png", "jpg", "jpeg", "heic", "mov", "mp4"],
             olderThanDays: 30, ageBasis: .added, deleteMode: .trash, autoClean: false,
             includeNames: ["Screenshot*", "Screen Shot*", "Screen Recording*", "Ảnh màn hình*", "Bản ghi màn hình*",
                            "Chụp màn hình*", "CleanShot*"]),
        Rule(id: "sys.downloads-old", name: "Mọi file cũ trong Downloads",
             detail: "Tất cả file/thư mục đã tải về hơn N ngày. Chuyển vào Thùng rác.",
             category: .system, safety: .review, kind: .contents,
             paths: ["~/Downloads"], olderThanDays: 90, ageBasis: .added, deleteMode: .trash, autoClean: false),
        Rule(id: "sys.largefiles", name: "File lớn lâu không mở",
             detail: "File từ N MB trở lên trong thư mục dự án, Movies, Music, Downloads… không mở trong N ngày. Chỉ để bạn rà soát; mặc định chuyển vào Thùng rác.",
             category: .system, safety: .review, kind: .largeFiles,
             paths: ["~/Movies", "~/Music", "~/Pictures", "~/Downloads", "~/Desktop", "~/Documents"],
             olderThanDays: 180, ageBasis: .accessed, deleteMode: .trash, autoClean: false, minSizeMB: 500),
        Rule(id: "sys.quicklook", name: "Cache ảnh xem trước Quick Look",
             detail: "Ảnh thu nhỏ do Finder/Quick Look tạo (qlmanage -r cache).",
             category: .system, safety: .safe, kind: .command,
             command: "qlmanage -r cache", autoClean: true),
        Rule(id: "sys.tmp", name: "File tạm cũ ($TMPDIR)",
             detail: "Mục trong thư mục tạm của bạn không được đụng tới trong N ngày.",
             category: .system, safety: .moderate, kind: .contents,
             paths: ["$TMPDIR"],
             excludeNames: ["com.apple.*", "*.sock", "*.lock", "*.pid", "TemporaryItems"], olderThanDays: 14, autoClean: false),
        Rule(id: "sys.caches-all", name: "Toàn bộ cache ứng dụng",
             detail: "Mọi thứ trong ~/Library/Caches (trừ của Apple), kể cả app đang dùng. App sẽ chậm hơn lúc đầu vì phải tạo lại cache.",
             category: .system, safety: .moderate, kind: .contents,
             paths: ["~/Library/Caches"], excludeNames: ["com.apple.*", "CloudKit", "FamilyCircle"], autoClean: false),
    ]
}
